spring:
  application:
    name: toylog

  datasource:
    url: jdbc:mysql://localhost:3306/toylog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57YcfPQye08f7MGVA9XkHa321455235
  expirationMs: 86400000

server:
  port: 80


